config/routes.rb
Rails.application.routes.draw do

 devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "jobs#index"

  resources :users, only: [:new, :create, :show] do
    resources :rubrics, only: [:new, :create, :show, :edit, :update]
    resources :events, only: [:index, :new, :create, :show]
    resources :notes, only: [:index, :new, :create, :show]
  end

  resources :networking_events

  resources :jobs, only: [:index, :new, :create, :show, :edit, :update] do
    resources :notes, only: [:new, :create, :update, :destroy]
    resources :events, only: [:new, :create, :show]
  end
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  has_many :events, as: :attendable
  has_many :notes, as: :notable
  
  # before_save :shorten_url

  def next_steps
    case
      when self.current_phase == "Accepted"
        return "YOU ARE AMAZING! CONGRATS!"
      when self.current_phase == "Offer"
        return "Call our DBC peeps for advice on salary negotiation."
      when self.current_phase == "Checking references"
        return "Make sure you have told your references that someone will be reaching out to them."
      when self.current_phase == "Onsite Interview"
        return "Research the people you're meeting with. Make sure you know where the interview is. Review algorithms."
      when self.current_phase == "Technical Phone Screen"
        return "Know the company's tech stack. Review algorithms."
      when self.current_phase == "Phone Screen"
        return "Practice giving your personal elevator pitch. Understand how your background can contribute to company goals."
      when self.current_phase == "Informational Interview"
        return "Develop a list of questions for your interviewer. Look them up on LinkedIn."
      when self.current_phase == "Applied"
        return "Go you! Now look up 5 people who work at the company and reach out to them!"
      when self.current_phase == "Wishlist"
        return "Research the company. Do you want to work there? Make sure it's aligned to your goals. Write a cover letter."
      end
  end

  def points 
    case
      when self.current_phase == "Accepted"
        return 1500
      when self.current_phase == "Offer"
        return 1000
      when self.current_phase == "Checking references"
        return 50
      when self.current_phase == "Onsite Interview"
        return 500
      when self.current_phase == "Technical Phone Screen"
        return 400
      when self.current_phase == "Phone Screen"
        return 300
      when self.current_phase == "Informational Interview"
        return 200
      when self.current_phase == "Applied"
        return 100
      when self.current_phase == "Wishlist"
        return 50
      end
  end 

  def self.total_job_points
    self.all.reduce(0) { |sum, job| sum + job.points}
  end

  # def shorten_url
  #   self.url = SecureRandom.hex(3)
  # end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  protect_from_forgery :except => [:create]

  def new
    @job = Job.new
  end

  def index

    if current_user
      @jobs = current_user.jobs.all
      @accepted_jobs = @jobs.where(current_phase: "Accepted")
      @offered_jobs = @jobs.where(current_phase: "Offer")
      @checking_references_jobs = @jobs.where(current_phase: "Checking References")
      @onsite_interview_jobs = @jobs.where(current_phase: "Onsite Interview")
      @phone_screen_jobs = @jobs.where(current_phase: "Technical Phone Screen")
      @info_interview_jobs = @jobs.where(current_phase: "Informational Interview")
      @applied_jobs = @jobs.where(current_phase: "Applied")
      @wishlist_jobs = @jobs.where(current_phase: "Wishlist")

        if !current_user.rubrics.last
          redirect_to current_user
        end
    else
      redirect_to new_user_session_path
    end
  end

  def show
    @job = current_user.jobs.find(params[:id])
    @note = Note.new
    @event = Event.new
  end

  def create
    if params[:job] #is this the form or the extension?
      @user = current_user
      @job = Job.new(
              url: params[:job][:url],
              company: params[:job][:company],
              job_title: params[:job][:job_title],
              description: params[:job][:description],
              user: @user,
              current_phase: "Wishlist"
              )
    else
      @user = User.find_by(email: params[:email])
      @job = Job.new(
              url: params[:url],
              company: params[:company],
              job_title: params[:job_title],
              description: params[:description],
              user: @user,
              current_phase: "Wishlist"
              )
    end
    @job.save

    respond_to do |format|
      format.html { redirect_to jobs_path }
      format.js
    end
  end

  def update
    @job = Job.find(params[:id])

    if params[:current_phase]
      if @job.update(current_phase: params[:current_phase])
        redirect_to @job
      else
        render 'edit'
     end
    else
      if @job.update(job_params)
        respond_to do |format|
          format.html { redirect_to job_path}
          format.js
        end
      else
        render :edit
      end
    end
  end

  def edit
    @job = Job.find(:id)
    @phases = ["Wishlist","Applied","Informational Interview","Phone Screen","Technical Phone Screen","Onsite Interview","Checking references","Offer","Accepted"]
  end

  private

  def job_params
    params.require(:job).permit(:criteria_one_score, :criteria_two_score, :criteria_three_score)
  end
end

app/helpers/jobs_helper.rb
module JobsHelper

end

app/views/jobs/_create_job.html.erb
<div id = "add-new-job">
<%= button_to "Add New Job", new_job_path, locals: { resource: current_user}, :method => :get, remote: true %>
</div>

app/views/jobs/_criteria_one.html.erb
<div id="criteria-one" style="display: flex">
  <% (1..5).each do |count| %>
      <%= form_for @job, remote: true do |f| %>
        <%= f.hidden_field :criteria_one_score, value: count %>
        <% if @job.criteria_one_score >= count %>
          <%= f.submit '♥' %>
        <% else %>
          <%= f.submit '♡' %>
        <% end %>
      <% end %>
    <% end %>
</div>

app/views/jobs/_criteria_three.html.erb
  <div id="criteria-three" style="display: flex">
  <% (1..5).each do |count| %>
    <%= form_for @job, remote: true do |f| %>
      <%= f.hidden_field :criteria_three_score, value: count %>
      <% if @job.criteria_three_score >= count %>
        <%= f.submit '♥' %>
      <% else %>
        <%= f.submit '♡' %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/jobs/_criteria_two.html.erb
<div id="criteria-two" style="display: flex">
   <% (1..5).each do |count| %>
 <%= form_for @job, remote: true do |f| %>
    <%= f.hidden_field :criteria_two_score, value: count %>
      <% if @job.criteria_two_score >= count %>
        <%= f.submit '♥' %>
      <% else %>
    <%= f.submit '♡' %>
    <% end %>
  <% end %>
 <% end %>
</div>

app/views/jobs/_edit.html.erb
<div class ="love-icon" style="display: flex">
  <ul>
    <h4> <%= current_user.rubrics.last.standard_one %> </h4>
    <p><%= render partial: 'criteria_one', locals: { job: @job } %></p>
  </ul>
</div>

<div class ="love-icon" style="display: flex">
  <ul>
    <h4> <%= current_user.rubrics.last.standard_two %>  </h4>
    <p><%= render partial: 'criteria_two', locals: { job: @job } %></p>
  </ul>
</div>

<div class ="love-icon" style="display: flex">
  <ul>
    <h4> <%= current_user.rubrics.last.standard_three %>  </h4>
    <p><%= render partial: 'criteria_three', locals: { job: @job } %></p>
  </ul>
</div>

app/views/jobs/_edit_current_phase.html.erb
<%= form_tag job_path(@job), :method => :put  do |form| %>

    <% if @job.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@job.errors.count, "error") %> prohibited
          this job from being saved:
        </h2>
        <ul>
          <% @job.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

<%= select_tag "current_phase", options_for_select(["Wishlist","Applied","Informational Interview","Phone Screen","Technical Phone Screen","Onsite Interview","Checking references","Offer","Accepted"], :selected => @job.current_phase) %>
  <%= submit_tag "Job Phase", name: nil, class: 'btn' %>

  <% end %>
</div>

app/views/jobs/_new.html.erb
<h2> Add a New Job </h2>

<br>

<div id = "new-job-create">
  <%= form_for @job, remote: true do |f| %>
  <input type="hidden" name="job[user_id]" value="<%= current_user.id %>" />
    <%= f.text_area :url, placeholder: "Paste Link Here" %>
    <%= f.text_area :company, placeholder: "Company Name" %>
    <%= f.text_area :job_title, placeholder: "Job Title" %>
    <%= f.text_area :description, placeholder: "Job Description" %>
    <%= f.submit "Submit" %>
  <% end %>
</div>

app/views/jobs/_wish_list.html.erb
<div class='list_item'><%= link_to job.job_title, job_path(job.id) %> at <%= job.company %></div>

app/views/jobs/create.js.erb
$('#wish-list').append('<%= j render partial: "jobs/wish_list", locals: { job: @job } %> ' );
$('#new-job-create').html('<%= j render partial: "jobs/create_job" %> ' );

app/views/jobs/index.html.erb
<h1>Hi, <%= current_user.first_name.capitalize %>!</h1>

<h2>Here's What's on Your Radar...</h2>

<br>

<div>
  <% if @accepted_jobs.any? %><h3>Accepted</h3>
    <% @jobs.each do |job| %>
      <% if job.current_phase == "Accepted" %>
         <%= render partial: "wish_list.html.erb", locals: {job: job} %>
      <% end %>
    <%end %>
    <br>
  <% end %>
</div>

<div>
  <% if @offered_jobs.any? %><h3>Offer</h3>
    <% @jobs.each do |job| %>
      <% if job.current_phase == "Offer" %>
         <%= render partial: "wish_list.html.erb", locals: {job: job} %>
      <% end %>
    <%end %>
    <br>
  <% end %>
</div>

<div>
  <% if @checking_references_jobs.any? %><h3>Checking References</h3>
    <% @jobs.each do |job| %>
      <% if job.current_phase == "Checking References" %>
         <%= render partial: "wish_list.html.erb", locals: {job: job} %>
      <% end %>
    <%end %>
    <br>
  <% end %>
</div>

<div>
  <% if @onsite_interview_jobs.any? %><h3>Onsite Interview</h3>
    <% @jobs.each do |job| %>
      <% if job.current_phase == "Onsite Interview" %>
         <%= render partial: "wish_list.html.erb", locals: {job: job} %>
      <% end %>
    <%end %>
    <br>
  <% end %>
</div>

<div>
  <% if @phone_screen_jobs.any? %><h3>Technical Phone Screen</h3>
    <% @jobs.each do |job| %>
      <% if job.current_phase == "Technical Phone Screen" %>
         <%= render partial: "wish_list.html.erb", locals: {job: job} %>
      <% end %>
    <%end %>
    <br>
  <% end %>
</div>

<div>
  <% if @info_interview_jobs.any? %><h3>Informational Interview</h3>
    <% @jobs.each do |job| %>
      <% if job.current_phase == "Informational Interview" %>
         <%= render partial: "wish_list.html.erb", locals: {job: job} %>
      <% end %>
    <%end %>
    <br>
  <% end %>
</div>

<div>
  <% if @applied_jobs.any? %><h3>Applied</h3>
    <% @jobs.each do |job| %>
      <% if job.current_phase == "Applied" %>
        <%= render partial: "wish_list.html.erb", locals: {job: job} %>
      <% end %>
    <%end %>
    <br>
  <% end %>
</div>

<div id="wish-list">
  <% if @wishlist_jobs.any? %>
  <h3>Wishlist</h3>
    <% @jobs.each do |job| %>
      <% if job.current_phase == "Wishlist" %>
        <%= render partial: "wish_list.html.erb", locals: {job: job} %>

      <% end %>
    <% end %>
  <% end %>
</div>

<br>

<div id = "add-new-job">
<%= button_to "Add New Job", new_job_path, locals: { resource: current_user}, :method => :get, remote: true %>
</div>

app/views/jobs/new.html.erb
<h2> Add a New Job </h2>

<br>

<div>
  <%= form_for @job do |f| %>
  <input type="hidden" name="job[user_id]" value="<%= current_user.id %>" />
    <%= f.text_area :url, placeholder: "Paste Link Here" %>
    <%= f.text_area :company, placeholder: "Company Name" %>
    <%= f.text_area :job_title, placeholder: "Job Title" %>
    <%= f.text_area :description, placeholder: "Job Description" %>
    <%= f.submit "Submit" %>
  <% end %>
</div>

app/views/jobs/new.js.erb
$('#add-new-job').html('<%= j render partial: "jobs/new", locals: { job: @job } %> ' );

app/views/jobs/show.html.erb
<h1> Get Geared Up to Work at <%= @job.company.capitalize %>, <%= current_user.first_name.capitalize %>!</h1>
<br>

<%= render partial: "edit_current_phase.html.erb", locals: {resource: @job} %>

<%= link_to "Create a new event", new_job_event_path(@job, @event) %>

<div>
  <h2>Here are your next steps:</h2>
  <p><%= @job.next_steps %></p>
</div>
<br>

<div class="job-info">
  <div class="job-section-header">
    <h3> <%= @job.company.capitalize %></h3>
  </div>

  <p><%= link_to @job.url, @job.url %></p>
  <h4><%= @job.job_title %>
  <h5><%= @job.description %></h5>
</div>
<br>

<h3> Job Ranking: </h3>

<br>

<%= render partial: "edit.html.erb", locals: {resource: @job} %>

<%= render partial: "notes/show.html.erb", locals: {resource: @job} %>

<%= render partial: "notes/new.html.erb", locals: {resource: @job} %>

app/views/jobs/update.js.erb
$('#criteria-two').html('<%= j render partial: "criteria_two", locals: { job: @job } %> ' );
$('#criteria-one').html('<%= j render partial: "criteria_one", locals: { job: @job } %> ' );
$('#criteria-three').html('<%= j render partial: "criteria_three", locals: { job: @job } %> ' );