config/routes.rb
Rails.application.routes.draw do

 devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "jobs#index"

  resources :users, only: [:new, :create, :show] do
    resources :rubrics, only: [:new, :create, :show, :edit, :update]
    resources :events, only: [:index, :new, :create, :show]
    resources :notes, only: [:index, :new, :create, :show]
  end

  resources :networking_events

  resources :jobs, only: [:index, :new, :create, :show, :edit, :update] do
    resources :notes, only: [:new, :create, :update, :destroy]
    resources :events, only: [:new, :create, :show]
  end
end

app/models/event.rb
class Event < ApplicationRecord

  belongs_to :attendable, polymorphic: true

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    current_user
    @events = current_user.events.all
  end

  def new
    @job = Job.find(params[:job_id])
    @event = Event.new
  end

  def create
    p "*" * 10
    p "&"* 100
    p event_params
    @job = Job.find(params[:job_id])
    p params
    @event = @job.events.new(event_params)
    if @event.save
      redirect_to @job
    else
      p @errors
      @errors = @event.errors.full_messages
      render :new
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :location, :datetime, :attendable_id, :attendable_type)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/calendars.html.erb
<h1>calendar view</h1>

<%= @summary_stuff %>

app/views/events/index.html.erb
<h1>Here are your upcoming job events...</h1>

<div class="events=list">
  <% @events.each do |e| %>
  <ul>
    <strong><%= e.title %></strong>
    <li><strong>Location:</strong> <%= e.location %></li>
    <li><strong>Event time:</strong> <%= e.datetime.strftime("%B, %-d at %l:%M %p ")%></li>
    <li><strong>Event details:</strong> <%= e.description %></li>
  </ul>
  <% end %>
</div>

app/views/events/new.html.erb
<h1>Create a new job event</h1>

<div id="add-event-form">
    <%= form_for @event, url: job_events_path, html: {class: "btn"} do |f| %>
    <%= f.hidden_field :user_id, value: @job.user_id %>
    <%= f.hidden_field :attendable_type, value: "job" %>
    <%= f.hidden_field :attendable_id, value: @job.id %>
    Event name: <%= f.text_field :title %>
    Location or Phone: <%= f.text_field :location %>
    Event details: <%= f.text_field :description%>
    Event time and date: <%= f.datetime_local_field :datetime%>

    <%= f.submit "Add a new event" %>
  <% end %>

</div>