config/routes.rb
Rails.application.routes.draw do

 devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "jobs#index"

  resources :users, only: [:new, :create, :show] do
    resources :rubrics, only: [:new, :create, :show, :edit, :update]
    resources :events, only: [:index, :new, :create, :show]
    resources :notes, only: [:index, :new, :create, :show]
  end

  resources :networking_events

  resources :jobs, only: [:index, :new, :create, :show, :edit, :update] do
    resources :notes, only: [:new, :create, :update, :destroy]
    resources :events, only: [:new, :create, :show]
  end
end

app/views/layouts/_errors.html.erb
<% if @errors %>
  <div id="error_explanation">
    <ul>
      <% @errors.each do |error| %>
        <li><%= error%></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobLand</title>
    <%= csrf_meta_tags %>

    <!-- Google Fonts -->
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic">

    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto+Slab">

    <!-- CSS Reset -->
    <link rel="stylesheet" href="//cdn.rawgit.com/necolas/normalize.css/master/normalize.css">

    <!-- Milligram CSS minified -->
    <link rel="stylesheet" href="//cdn.rawgit.com/milligram/milligram/master/dist/milligram.min.css">

    <link rel="icon" type="image/png" href="/images/JL_logo.png">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

        <% if user_signed_in? %>
          <nav class= "navbar">
            <li id='logo-li'><img id="logo" src="/images/JL_logo.png" width="40" height="40"></li>
        <!-- <ul id="navbar"> --> 
                <li> <%= link_to "Profile", user_path(current_user.id) %> </li>
                <li> <%= link_to "My Jobs", root_path(current_user.id) %> </li>
                <li> <%= link_to "Calendar", user_events_path(current_user.id) %></li>
                <li> <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>
              <div id = profile-pic>
                 <li id = "welcome"> </li>
                 <img id='profile-picture-image' src="<%= current_user.profile_picture %>"/>
              </div>
        <!-- </ul> -->
          </nav>
        <% else %>
          <img id="logo" src="/images/JL_logo.png" width="40" height="40">
          <nav id="homepage-button">
            <%= link_to "Login with Google", user_google_oauth2_omniauth_authorize_path %>
          </nav>
        <% end %>
      <br>
    <%= render partial: "layouts/errors", layout: false %>
    <%= yield %>


  </body>
</html>